### ISSUE TITLE
n8n doesn't see API

### ISSUE THREAD

**Issue by Zeraxel** [jonatanjacobsson/ifcpipeline#1]
Hi! I faced a problem when working with ifcpipeline. when starting the process n8n does not see the API, neither at http://ifcpipeline:8000/ nor http://localhost:8000. At the same time http://localhost:8000 in the browser works and http://localhost:8000/docs shows all methods. I attach a screenshot.
![2024-09-11_13-36-57](https://github.com/user-attachments/assets/8744b7d0-0b1f-42a9-abf3-b6fb61358068)
![2024-09-11_13-37-17](https://github.com/user-attachments/assets/6e6abb90-71d0-448c-a8ed-c30c2b90a44c)

**Comment by Zeraxel** [comment]
Found the reason. Instead of 'ifcpipeline:8000' you should use 'api-gateway:80'

**Comment by jonatanjacobsson** [comment]
Thanks for reporting @Zeraxel! yeah ill update the docs and the screenshots. 
Im also planning on sharing some n8n nodes aswell that can be pasted into the workflow editor.

**Comment by jonatanjacobsson** [comment]
for reference, this is where you set the gateway adress in the docker-compose file:
![image](https://github.com/user-attachments/assets/15f8f5b6-3a35-4e28-bf77-1cae8823db39)
